---
### Install Microsoft SQL Server 2017 Developer Edition covering all needed dependencies ###

# Load required powershell modules
- name: Powershell | Check for SQLServer DSC Powershell module
  win_psmodule:
    name: SQLServerDsc
    state: present

- name: Powershell | Check for Storage DSC Powershell module
  win_psmodule:
    name: StorageDsc
    state: present

- name: Powershell | Ensure that DBA Tools module is present
  win_psmodule:
    name: dbatools
    state: present

- name: Powershell | Check for xNetworking Powershell module
  win_psmodule:
    name: xNetworking
    state: present


# Setup SQL Server Pre-Requisites
- name: Windows | Install .NET Framework Core
  win_feature:
    name: NET-Framework-Core
    state: present

- name: Windows | Install .NET Framework 4.5 Features
  win_feature:
    name: NET-Framework-45-Features
    state: present
    include_sub_features: True

- name: Windows | Install Windows Process Activation Service
  win_feature:
    name: WAS
    state: present
    include_sub_features: True


# Setup new domain and turn the server to a domain controller
- name: Active Directory Domain Services | Create new domain in a new forest on the target host
  win_domain:
    dns_domain_name: "{{ dns_domain_name }}"
    safe_mode_password: "{{ dns_safe_mode_pass }}"
  register: domain_install

- name: Windows Reboot | Reboot Windows when domain install requires it
  win_reboot:
    reboot_timeout: 3600
    post_reboot_delay: 120
  when: domain_install.reboot_required

- name: Active Directory Domain Services | Ensure Windows server is a domain controller
  win_domain_controller:
    dns_domain_name: "{{ dns_domain_name }}"
    domain_admin_user: "{{ dns_domain_admin_user }}"
    domain_admin_password: "{{ dns_domain_admin_pass }}"
    safe_mode_password: "{{ dns_safe_mode_pass }}"
    state: domain_controller
    log_path: "{{ dns_log_path }}"
  register: domain_controller_check

- name: Windows Reboot | Reboot Windows when domain controller requires it
  win_reboot:
    reboot_timeout: 3600
    post_reboot_delay: 300
  when: domain_controller_check.reboot_required

- pause:
    prompt: "Pausing for 5 more minutes to have the AD services up and ready in the target host to start setting up service accounts" 
    minutes: 5


# Setup service accounts
# We delegate this process to our domain controller since the required AD services are there for win_domain_user to interact with. 
- name: Active Directory | Ensure SQL Service account is present
  win_domain_user:
    name: "{{ mssql_sqlsvc_account | regex_search('[^\\\\]*$') }}"
    firstname: "{{ mssql_instance_name }}"
    surname: SQLSvc
    password: "{{ mssql_sqlsvc_account_pass }}"
    password_never_expires: yes
    user_cannot_change_password: yes
    description: "SQL Service account for {{ inventory_hostname }}\\{{ mssql_instance_name }}"
    state: present
    path: "{{ mssql_base_ldap_path }}"
    groups:
      - Domain Users
  tags: service_account
  delegate_to: "{{ domain_controller }}"

- name: Active Directory | Ensure SQL Agent Service account is present
  win_domain_user:
    name: "{{ mssql_agentsvc_account | regex_search('[^\\\\]*$') }}"
    firstname: "{{ mssql_instance_name }}"
    surname: AgentSvc
    password: "{{ mssql_agentsvc_account_pass }}"
    password_never_expires: yes
    user_cannot_change_password: yes
    description: "SQL Agent service account for {{ inventory_hostname }}\\{{ mssql_instance_name }}"
    state: present
    path: "{{ mssql_base_ldap_path }}"
    groups:
      - Domain Users
  delegate_to: "{{ domain_controller }}"
  tags: service_account


# Install Sql Server Management Studio (SSMS)
- name: Install SSMS | Installing SQL Server Management Studio
  win_shell: "{{ lookup('file', 'ssms_install.ps1') }}"


# SQL install may fail if a pending reboot is detected
# Assuming we are allowed to reboot this step will check for pending reboots
# and execute a reboot, reboot activity can be controlled using the variable mssql_suppress_reboot
- name: Windows Reboot | Check for pending reboot
  win_shell: "{{ lookup('file', 'check_pending_reboot.ps1') }}"
  register: pending_reboot
  changed_when: pending_reboot.stdout_lines[0] != 'False'
  notify: 
    - reboot windows

- name: run all notified handlers
  meta: flush_handlers


# Start of the installation of MS SQL Server 2017
- name: SQL Server Install | Create temporary directory
  win_file:
    path: "{{ mssql_temp_download_path }}"
    state: directory

- name: SQL Server Install | Fetch SQL Media Downloader
  win_get_url:
    url: "{{ mssql_installation_source }}"
    dest: "{{ mssql_temp_download_path }}\\SQLServer2017-SSEI-Dev.exe"

- name: SQL Server Install | Use Media Downloader to fetch SQL Installation CABs to {{ mssql_installation_path }}
  win_shell: "{{ mssql_temp_download_path }}\\SQLServer2017-SSEI-Dev.exe /Action=Download /MediaPath={{ mssql_installation_path }} /MediaType=CAB /Quiet"

# Job will fail if extracted media folder is not empty, quick step to ensure it's empty
- name: SQL Server Install | Ensure installation media extraction path is empty
  win_file:
    path: "{{ mssql_installation_path }}\\Media"
    state: absent

- name: SQL Server Install | Extract installation media
  win_shell: "{{ mssql_installation_path }}\\SQLServer2017-DEV-x64-ENU.exe /X:{{ mssql_installation_path }}\\Media /Q"
# If this step fails, logs are in C:\Program Files\Microsoft SQL Server\...\Setup Bootstrap\Log
# it will often contain the actual error.  If it shows everything passing, the issue is within the DSC logs.
# 
# This module also typically throws this error for all failure conditions:
# PowerShell DSC resource MSFT_SqlSetup  failed to execute Set-TargetResource functionality with error message: 
# System.Exception: Test-TargetResource returned false after calling Set-TargetResource.
#
#
# This document can also be useful to troubleshoot issues with DSC modules
# https://docs.microsoft.com/en-us/powershell/dsc/troubleshooting 
#
# In particular completing these steps:
# https://docs.microsoft.com/en-us/powershell/dsc/troubleshooting#gathering-events-from-a-single-dsc-operation
# then re-running a failing PowershellDSC job can help you find the source of your error
- name: SQL Server Install | Installing SQL Server 2017 Developer Edition
  win_dsc:
    resource_name: SQLSetup
    Action: Install
    UpdateEnabled: True
    SourcePath: "{{ mssql_installation_path }}\\Media"
    InstanceName: "{{ mssql_instance_name }}"
    InstallSharedDir: "{{ mssql_installshared_path }}"
    InstallSharedwowDir: "{{ mssql_installsharedwow_path }}"
    InstanceDir: "{{ mssql_instance_path }}"
    InstallSQLDataDir: "{{ mssql_sqlinstalldata_path }}"
    SQLUserDBDir: "{{ mssql_sqluserdata_path }}"
    SQLUserDBLogDir: "{{ mssql_sqluserlog_path }}"
    SQLTempDBDir: "{{ mssql_sqltempDB_path }}"
    SQLTempDBLogDir: "{{ mssql_sqltempDBlog_path }}"
    Features: "{{ mssql_features }}"
    SQLCollation: "{{ mssql_collation }}"
    BrowserSvcStartupType: "{{ mssql_browsersvc_mode }}"
    SuppressReboot: "{{ mssql_suppress_reboot }}"
    # Service Accounts
    #
    # If the type of the DSC resource option is a PSCredential then 
    # there needs to be 2 options set in the Ansible task definition 
    # suffixed with _username and _password. So we will be providing 
    # two options for these normally single option items.

    # SQL Service Account
    SQLSvcAccount_username: "{{ mssql_sqlsvc_account }}"
    SQLSvcAccount_password: "{{ mssql_sqlsvc_account_pass }}"
    # SQL Agent Service Account
    AgtSvcAccount_username: "{{ mssql_agentsvc_account }}"
    AgtSvcAccount_password: "{{ mssql_agentsvc_account_pass }}"
    # SQL Analysis Services Account
    ASSvcAccount_username: "{{ mssql_assvc_account }}"
    ASSvcAccount_password: "{{ mssql_assvc_account_pass }}"

    # Used when installing on a network path, comment out 
    # SourceCredential_username: "{{ ansible_user }}"
    # SourceCredential_password: "{{ ansible_password }}"

    # System Admins 
    SQLSysAdminAccounts: "{{ mssql_sysadmin_accounts }}"
    # Analysis Services Admins (if installed)
    ASSysAdminAccounts: "{{ mssql_asadmin_accounts }}"
  tags: install_sql

# End of win_dsc for SQL Server


# Firewall configuration
- name: Firewall | Allow Database Engine for instance
  win_dsc:
    resource_name: xFirewall
    Name: "SQL Server Database Engine instance {{ mssql_instance_name }}"
    Program: sqlservr.exe 
    Ensure: present
    Enabled: True
    Profile: "Domain"
    Direction: "Inbound"
    Action: Allow
    Description: "Allows the Database Engine to access the network"  
  tags: configure_firewall

- name: Firewall | Allow SQLBrowser for instance
  win_dsc:
    resource_name: xFirewall
    Name: "SQL Server Browser instance {{ mssql_instance_name }}"
    Service: SQLBrowser
    Ensure: present
    Enabled: True
    Profile: "Domain"
    Direction: "Inbound"
    Action: Allow
    Description: "Allows the SQL Server Browser to access the network"  
  tags: configure_firewall


# Begin SQL Server configuration
- name: SQL Server Config | Enable TCP Connectivity
  win_dsc:
    resource_name: SqlServerNetwork
    InstanceName: "{{ mssql_instance_name }}"
    ProtocolName: tcp
    TcpPort: "{{ mssql_port }}"
    IsEnabled: True
    RestartService: True
  tags: configure_sql

- name: SQL Server Config | Adjust Max and Min Server Memory to {{ mssql_max_server_memory }} and {{ mssql_min_server_memory }} respectively
  when: mssql_max_server_memory and mssql_min_server_memory is defined
  win_dsc:
    resource_name: SqlMemory
    InstanceName: "{{ mssql_instance_name }}"
    ServerName: "{{ ansible_hostname }}"
    MaxMemory: "{{ mssql_max_server_memory }}"
    MinMemory: "{{ mssql_min_server_memory }}"
  tags: configure_sql

- name: SQL Server Config | Adjust Max Degree of Parallelism
  when: mssql_max_degree_of_parallelism is defined
  win_dsc:
    resource_name: SqlMaxDop 
    ServerName: "{{ ansible_hostname }}"
    InstanceName: "{{ mssql_instance_name }}"
    MaxDop: "{{ mssql_max_degree_of_parallelism }}"
  tags: configure_sql


# Final check for Windows pending reboot to have the changes take effect or apply
- name: Windows Reboot | Final check for pending reboot
  win_shell: "{{ lookup('file', 'check_pending_reboot.ps1') }}"
  register: pending_reboot
  changed_when: pending_reboot.stdout_lines[0] != 'False'
  notify: 
    - reboot windows

- name: run all notified handlers
  meta: flush_handlers


# Enabling mixed mode authentication
- name: Enable Mixed mode Authentication | Runs a Powershell script to enable mixed mode Authentication
  win_shell: "{{ lookup('file', 'mixed-mode-auth.ps1') }}"


# Enabling "sa" user for SQL Server Authentication mode using Transact-SQL queries
- name: Run Query | T-Sql queries to enable "sa" account for SQL Server Authentication mode
  win_shell: "{{ lookup('file', 'sauser-enable.ps1') }}"
  register: query_result
  notify:
    - restart sqlserver service
    - restart sqlagent service

- name: run all notified handlers
  meta: flush_handlers


# Password reset for 'sa' user to have this login work
- name: Password reset for sa user | Reset password for sa user to have this login work
  win_command: osql -S "<Windows host name>\TEST" -E -Q "exec sp_password NULL,'StrngPa$$@3','sa'"

# Run some sample queries
#- name: Run Query | Sample queries to create a database and a table
#  win_shell: "{{ lookup('file', 'sqlserver_queries.ps1') }}"
#  register: query_result
